/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ufes.view;

import com.mycompany.collection.OrdenarCollection;
import com.mycompany.presenter.ManipuladorArquivoPresenter;
import com.mycompany.presenter.OrdenarPresenter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author ruanr
 */
public class OrdenacaoView extends javax.swing.JFrame {

    private OrdenarCollection salarios;
    /**
     * @param lstSemOrdem the lstSemOrdem to set
     */
    public void setLstSemOrdem(javax.swing.JTextArea lstSemOrdem) {
        this.lstSemOrdem = lstSemOrdem;
    }

    /**
     * @return the grpOrdem
     */
    public javax.swing.ButtonGroup getGrpOrdem() {
        return grpOrdem;
    }

    /**
     * @return the btnOrdernar
     */
    public javax.swing.JButton getBtnOrdernar() {
        return btnOrdernar;
    }

    /**
     * @return the btnCarregarArquivo
     */
    public javax.swing.JButton getBtnCarregarArquivo() {
        return btnCarregarArquivo;
    }

    /**
     * @return the cmbMetodo
     */
    public javax.swing.JComboBox<String> getCmbMetodo() {
        return cmbMetodo;
    }

    /**
     * @return the lblMetodoOrdenacao
     */
    public javax.swing.JLabel getLblMetodoOrdenacao() {
        return lblMetodoOrdenacao;
    }

    /**
     * @return the lblOrdem
     */
    public javax.swing.JLabel getLblOrdem() {
        return lblOrdem;
    }

    /**
     * @return the lblOrdenados
     */
    public javax.swing.JLabel getLblOrdenados() {
        return lblOrdenados;
    }

    /**
     * @return the lblSemOrdem
     */
    public javax.swing.JLabel getLblSemOrdem() {
        return lblSemOrdem;
    }

    /**
     * @return the lblTempo
     */
    public javax.swing.JLabel getLblTempo() {
        return lblTempo;
    }

    /**
     * @return the lstOrdenados
     */
    public javax.swing.JTextArea getLstOrdenados() {
        return lstOrdenados;
    }

    /**
     * @return the lstSemOrdem
     */
    public javax.swing.JTextArea getLstSemOrdem() {
        return lstSemOrdem;
    }

    /**
     * @return the rbtnCrescente
     */
    public javax.swing.JRadioButton getRbtnCrescente() {
        return rbtnCrescente;
    }

    /**
     * @return the rbtnDecrescente
     */
    public javax.swing.JRadioButton getRbtnDecrescente() {
        return rbtnDecrescente;
    }

    /**
     * Creates new form PrincipalView
     */
    public OrdenacaoView() {
        initComponents();
        
        salarios = new OrdenarCollection();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpOrdem = new javax.swing.ButtonGroup();
        lblSemOrdem = new javax.swing.JLabel();
        lblOrdenados = new javax.swing.JLabel();
        Jscroll1 = new javax.swing.JScrollPane();
        lstSemOrdem = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstOrdenados = new javax.swing.JTextArea();
        btnCarregarArquivo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblTempo = new javax.swing.JLabel();
        btnOrdernar = new javax.swing.JButton();
        lblOrdem = new javax.swing.JLabel();
        rbtnCrescente = new javax.swing.JRadioButton();
        rbtnDecrescente = new javax.swing.JRadioButton();
        cmbMetodo = new javax.swing.JComboBox<>();
        lblMetodoOrdenacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSemOrdem.setText("Elementos a serem ordenados:");

        lblOrdenados.setText("Elementos ordenados:");

        lstSemOrdem.setColumns(20);
        lstSemOrdem.setRows(5);
        Jscroll1.setViewportView(lstSemOrdem);

        lstOrdenados.setColumns(20);
        lstOrdenados.setRows(5);
        jScrollPane2.setViewportView(lstOrdenados);

        btnCarregarArquivo.setText("Carregar novo arquivo...");
        btnCarregarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarArquivoActionPerformed(evt);
            }
        });

        jLabel3.setText("Tempo:");

        lblTempo.setText("0ms");

        btnOrdernar.setText("Ordernar");
        btnOrdernar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdernarActionPerformed(evt);
            }
        });

        lblOrdem.setText("Ordem:");

        grpOrdem.add(rbtnCrescente);
        rbtnCrescente.setSelected(true);
        rbtnCrescente.setText("Crescente");
        rbtnCrescente.setToolTipText("");
        rbtnCrescente.setActionCommand("crescente");

        grpOrdem.add(rbtnDecrescente);
        rbtnDecrescente.setText("Decrescente");

        cmbMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BubbleSort", "SelectionSort" }));
        cmbMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMetodoActionPerformed(evt);
            }
        });

        lblMetodoOrdenacao.setText("Metodo de ordenacao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCarregarArquivo)
                            .addComponent(Jscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cmbMetodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(btnOrdernar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtnCrescente))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtnDecrescente))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblOrdem))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMetodoOrdenacao)))
                                .addGap(0, 43, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSemOrdem)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTempo))
                    .addComponent(lblOrdenados))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMetodoOrdenacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblOrdem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnCrescente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnDecrescente)
                        .addGap(29, 29, 29)
                        .addComponent(btnOrdernar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSemOrdem)
                            .addComponent(lblOrdenados))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Jscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarregarArquivo)
                    .addComponent(jLabel3)
                    .addComponent(lblTempo))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMetodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMetodoActionPerformed

    private void btnCarregarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarArquivoActionPerformed
        
        ManipuladorArquivoPresenter presenter = new ManipuladorArquivoPresenter(salarios);
        
        String str = "";
        for (Double salario : salarios.getSalarios()) {
            str += salario.toString() + "\n";
        }
        getLstSemOrdem().setText(str);
    }//GEN-LAST:event_btnCarregarArquivoActionPerformed

    private void btnOrdernarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdernarActionPerformed
        // TODO add your handling code here:
        String method = getCmbMetodo().getSelectedItem().toString().toUpperCase();
        
        long startTime = System.nanoTime();
        
        OrdenarPresenter presenter = new OrdenarPresenter(salarios, method);
        
        if(! getRbtnCrescente().isSelected() ) {
            Collections.sort(salarios.getSalarios(), Collections.reverseOrder());
        }
   
        long endTime = System.nanoTime();
        long timeElapsed = endTime - startTime;
        String strElapsed = ""+ (timeElapsed/1000000);
        
        getLblTempo().setText(strElapsed+"ms");
        /// "toString" pra exibir a lista ordenada
        String str = "";
        for (Double salarioOrdenado : salarios.getSalarios()) {
            str += salarioOrdenado.toString() + "\n";
        }
        getLstOrdenados().setText(str);
        
    }//GEN-LAST:event_btnOrdernarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Jscroll1;
    private javax.swing.JButton btnCarregarArquivo;
    private javax.swing.JButton btnOrdernar;
    private javax.swing.JComboBox<String> cmbMetodo;
    private javax.swing.ButtonGroup grpOrdem;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMetodoOrdenacao;
    private javax.swing.JLabel lblOrdem;
    private javax.swing.JLabel lblOrdenados;
    private javax.swing.JLabel lblSemOrdem;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JTextArea lstOrdenados;
    private javax.swing.JTextArea lstSemOrdem;
    private javax.swing.JRadioButton rbtnCrescente;
    private javax.swing.JRadioButton rbtnDecrescente;
    // End of variables declaration//GEN-END:variables
}
